### ISSUE TITLE
Enable categorization in Moran & Markov analyses

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/crankshaft#168]
**What:**

Add a field to categorize the analysis, so the user can run it N times at once if there are N parameters under study at each point, and you want to analyze them independently.

Like the centroid one:

![selection_001](https://cloud.githubusercontent.com/assets/9017165/22241790/3d8a2c66-e221-11e6-83ea-1f565ba9de1e.png)

**Why:**

Real life example: air quality monitoring stations. Each of them measures several parameters (let's call them categories) like NO, NO2, CO, CO2, PM25, PM10, etc. If you run Moran or Markov as is, it will mess with all the values and drive crazy because you have several values at the same point (and time). So you need to create N nodes first, filtering by category, and then apply Moran/Markov N times, once per node.

cc @stuartlynn  @saleiva

**Comment by ohasselblad** [comment]
Hey @AbelVM, that'd be awesome to have that ability! This seems more of a camshaft / UI thing than something that's in crankshaft, because the query that would need to be run could easily be generated in camshaft:

```sql
SELECT 
  p.*,
  m1.quads as quads_no2, 
  m1.significance as sig_no2, 
  m2.quads as quads_pm25, 
  m2.significance as sig_pm25, 
  ...
FROM 
  pollution_data As t
JOIN
  cdb_crankshaft.cdb_areasofinterestlocal('select * from pollution_data', 'no2') As m1
ON m1.rowid = t.cartodb_id
JOIN
  cdb_crankshaft.cdb_areasofinterestlocal('select * from pollution_data', 'pm25') As m2
ON m2.rowid = t.cartodb_id
```

I've seen discussion about having other analyses return multiple measures (like the data observatory). While that is different, it seems that we could offer a more generic framework for analyses working off of multiple columns instead of laboriously adding new nodes each time.

**Comment by AbelVM** [comment]
Feel free to move the conversation there! :grin:

cc @rochoa , just in case

**Comment by andy-esch** [comment]
Closing as it's a camshaft thing -> CartoDB/camshaft#252
