### ISSUE TITLE
Add VIRTUALENV_PATH variable usage instructions to doc

### ISSUE THREAD

**Issue by rafatower** [CartoDB/crankshaft#21]
In my local install I have the source code under `/home/ubuntu/www/crankshaft`. When I ran `sudo make deploy` I got the following error when trying to run some function:
```
ERROR:  IOError: [Errno 2] No such file or directory: '/home/ubuntu/crankshaft/envs/0.0.2/bin/activate_this.py'
```

Apparently I need to define the path using the variable `VIRTUALENV_PATH` or otherwise it creates it on the root directory (within `/0.0.2`).

**Comment by rafatower** [comment]
my workaround:
```
mkdir -p /home/ubuntu/crankshaft/envs
sudo VIRTUALENV_PATH=/home/ubuntu/crankshaft/envs make deploy
```

**Comment by jgoizueta** [comment]
`VIRTUALENV_PATH` should have been defined in Makefile.global

**Comment by jgoizueta** [comment]
This has been fixed directly in master (as it is a fix of the deployment process), to be included in a future release.

**Comment by jgoizueta** [comment]
There's also a runtime issue, after having deployed the extension:

```sql
# CREATE EXTENSION CRANKSHAFT;
CREATE EXTENSION
# SELECT cdb_crankshaft._cdb_random_seeds(123);
ERROR:  spiexceptions.ExternalRoutineException: IOError: [Errno 2] No such file or directory: '/home/ubuntu/crankshaft/envs/0.0.2/bin/activate_this.py'
CONTEXT:  Traceback (most recent call last):
  PL/Python function "_cdb_random_seeds", line 2, in <module>
    plpy.execute('SELECT cdb_crankshaft._cdb_crankshaft_activate_py()')
PL/Python function "_cdb_random_seeds"
```

**Comment by jgoizueta** [comment]
Summary of the situation: In development we can use any directory and everything will work fine, but the release process fixes the directory used in development into the release code so releases can only be installed it that directory.

Since the releases are only done by the release manager we could live FTM with the convention of using the fixed path `/home/ubuntu/www/crankshaft/envs` for deploying in production; the developers can use whatever directory they wish, because they won't be creating releases.

**Comment by jgoizueta** [comment]
Note that use an environment variable `CRANKSHAFT_VENV` to override the virtual environments location, but it is rather ineffective and should be removed (or replaced by a better mechanism), since it would have to be defined in the environment running the postgresql server...

**Comment by rafatower** [comment]
Isn't this already fixed?

**Comment by jgoizueta** [comment]
The error when deploying is fixed. What's not fixed is that the path to the virtual environment used when generating the releasis *fixed* (hardcoded) into the extension, so in production that exact same path must be used for deployment (but we could live with this FTM).

And regarding the original tile of this issue, `VIRTUALENV_PATH` is still not documented, but I think we should remove it because it is not really useful (it's not easy to set environment variables accessible from the extension's python package). Should probably be replaced by something else (e.g. configuration in a table?)

**Comment by rafatower** [comment]
Ok, closing this. Hardcoding the path works for the moment.

Feel free to rename tickets' titles to accurately summarize the problems to solve.
