### ISSUE TITLE
DATOBS- Use actual geometries for the bounds for geom tables rather than `BOX`

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/crankshaft#34]
Update the bounding box references in the geometry tables to use actual geometries rather than box2d strings.

**Comment by talos** [comment]
Reviving this as https://github.com/CartoDB/bigmetadata/issues/40 is resolved.

Instead of using `bounds` in `obs_table`, there is a new column coming to the metadata called `the_geom`.  For tables that actually have geometries in them, this will be a very simplified `MULTIPOLYGON` approximating the outline of all the component geometries in that table.

We need to rewrite those sections of the OBS that use `bounds` to intersect against this column, instead.

**Comment by talos** [comment]
Replacing this as OBS functions are now in observatory-extension: https://github.com/CartoDB/observatory-extension/issues/116
