### ISSUE TITLE
Functions are not interruptible

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/crankshaft#67]
Right now, a `pg_cancel_backend($PID)` will not stop a Crankshaft query.

This causes long queries not being able to be killed by statement timeouts. Looks like PL/Python does not do proper handling of termination signals.

cc @rochoa

**Comment by zenitraM** [comment]
reproduced with `CDB_AreasOfInterestLocal`

cc @javisantana @luisico

**Comment by javisantana** [comment]
cc @andrewxhill @stuartlynn hey guys, this is a really important issue for us, all the functions should be interruptible somehow. 

at python level is hard to do I guess, the only thing that comes to my mind is to do the same than posgis does:

- call everything CPU attached in a python thread
- listen to SIGINT (https://github.com/postgis/postgis/blob/svn-trunk/postgis/postgis_module.c#L62) and kill the thread

**Comment by rafatower** [comment]
I don't know if it can be done but standard python supports signal handlers: https://docs.python.org/3/library/signal.html#example

If we need something else, chances are we have to modify the pl/python code, probably around these lines https://github.com/CartoDB/postgres/blob/master/src/pl/plpython/plpy_main.c#L188

**Comment by andrewxhill** [comment]
@stuartlynn is testing the explicit thread approach now

**Comment by stuartlynn** [comment]
So just a quick test here to see what database access we have if we spawn a child thread in python. This function:

```sql 

 CREATE OR REPLACE FUNCTION threading_test()                        
 returns text AS $$                                                 
                                                                    
 import threading                                                   
 import plpy                                                        
                                                                    
 class myThread (threading.Thread):                                 
     def __init__(self, threadID, name, q):                         
         threading.Thread.__init__(self)                            
         self.threadID = threadID                                   
         self.name = name                                           
         self.q = q                                                 
                                                                    
                                                                    
     def run(self):                                                 
         try:                                                       
             data = plpy.execute('select count(*) from customers')  
         except:                                                    
             data = 'failed'                                        
                                                                    
         self.result = data                                         
         return                                                     
                                                                    
 queue = Queue.Queue()                                              
                                                                    
                                                                    
                                                                    
 thread = myThread(1, "test", 1)                                    
 thread.start()                                                     
 thread.join()                                                      
                                                                    
 data = plpy.execute('select count(*) from customers')              
 plpy.notice( data)                                                 
 return thread.result                                               
 $$                                                                 
 LANGUAGE plpythonu;                                                
```

Returns 

```
cartodb_dev_user_218d9fde-34c1-4aea-b1b3-dadd7ef65a2a_db=# select * from threading_test();      
NOTICE:  <PLyResult status=5 nrows=1 rows=[{'count': 6429L}]>                                   
CONTEXT:  PL/Python function "threading_test"                                                   
 threading_test                                                                                 
----------------                                                                                
 failed                                                                                         
(1 row)            
```

So it looks like we don't have database access from spawned threads. This might be ok because we can grab data from the database upfront or as arguments passed in to the function then spawn the thread.

Not sure if this is the same as what you guys are talking about? Or if you would spawn a thread on the postgres side to run the python code then kill that. 

I think as long as we have database access then I think we are good to be running in a new thread.

**Comment by javisantana** [comment]
but the point is to do the CPU extensive functions inside the thread not the data fetching (which should be interrumpible)

**Comment by stuartlynn** [comment]
So in this example yeah totally we could call the plpy.execute function in the main python thread and then pass the data through to the subthread to process, but that still wouldn't let you interrupt the main python thread while its fetching the data would it? Or am I missing something?

**Comment by zenitraM** [comment]
I think we should check first if plpython functions are interruptible _at all_ (i.e: try to pg_terminate_backend a big loop of small sleeps so there's places in the middle where code can be stopped)

**Comment by zenitraM** [comment]
It seems you can indeed handle SIGINT from inside Python, this is interruptible:

```import signal
import sys
def signal_handler(signal, frame):
        print('You pressed Ctrl+C!')
        sys.exit(0)
signal.signal(signal.SIGINT, signal_handler)
print('Press Ctrl+C')
signal.pause()```

**Comment by rochoa** [comment]
What's the status of this issue? Who is working / gonna work on it?

**Comment by stuartlynn** [comment]
@zenitraM So is it enough for us to detect and handle that signal ? Basically if we detect it happening to shut down the processing thread and return?

**Comment by zenitraM** [comment]
It seems so, but test it with the functions as there might be some more implications due to running the native numpy/pysal extensions

**Comment by stuartlynn** [comment]
Sounds good. Will do a test and if it works I will write a class that we can start inheriting from in crankshaft that will automatically do the threading and handle the interrupt.

**Comment by javisantana** [comment]
hey, any update on this. This is a pretty important problem and could cause a lot of pain when controlling the database load

**Comment by rafatower** [comment]
test in postgres:
```sql
create or replace function test_interruptible()
returns void
as $$
  import time

  -- signal snippet
  import signal
  import sys
  def signal_handler(signal, frame):
    print('You pressed Ctrl+C!')
    sys.exit(0)
  signal.signal(signal.SIGINT, signal_handler)


  start = time.time()
  a = 0
  while (time.time() - start < 120):
    a = a+1
$$ language plpythonu;
```

output on the server after issuing the `pg_cancel_backend`:
```
tests=# select test_interruptible();
-- here the pg_cancel_backend
ERROR:  SystemExit: 0
CONTEXT:  Traceback (most recent call last):
  PL/Python function "test_interruptible", line 14, in <module>
    while (time.time() - start < 120):
  PL/Python function "test_interruptible", line 8, in signal_handler
    sys.exit(0)
PL/Python function "test_interruptible"
```

We tested with `time.sleep()` and it is interruptible without the signal handler, but with busy waiting it is not.

Maybe there's a more graceful way of dealing with it, rather than `sys.exit()`.

A suggestion: have the signal handler snippet into a `init()` function within the module's `__init__.py` and at the beginning of entry points use this pattern:
```python
import crankshaft
crankshaft.init()
```

**Comment by ethervoid** [comment]
To have into account:

[Although Python signal handlers are called asynchronously as far as the Python user is concerned, they can only occur between the “atomic” instructions of the Python interpreter. This means that signals arriving during long calculations implemented purely in C (such as regular expression matches on large bodies of text) may be delayed for an arbitrary amount of time.](https://docs.python.org/2/library/signal.html)

**Comment by ethervoid** [comment]
After working on this issue for a few days, I want to summarize the current status and what options do we have.

First of all, I want to show the multiple cases I've faced to try to interrupt crankshaft functions that mix both data fetching and CPU intensive operations:

- If we don't add a custom signal handler we're not able to interrupt the function when is performing CPU intensive operations. When the `SIGINT` signal is launched, the system waits until the function ends to be able to cancel it.
- If we add a custom signal handler for the `SIGINT`, we are able to interrupt the CPU intensive function but we're not able to interrupt data fetching operations like `plpy.execute(query)` because we have override the Postgres handler for that signal.
- As a third option I've added a python context manager to wrap, for testing purposes, the CPU intensive part (Moran function from PySAL):
```
def _signal_handler(signal_code, frame):
    plpy.error(INTERRUPTED BY USER!!')


@contextmanager
def interruptible():
    try:
        signal.signal(signal.SIGINT, _signal_handler)
        yield
    finally:
        # Restore the default behavoiur for the signal
        signal.signal(signal.SIGINT, signal.SIG_DFL)
```
  This doesn't work as expected because in the `finally` clause we try to reset to the default behavior but in Postgres the behavior for the SIGINT signal is defined by a [custom handler](https://github.com/postgres/postgres/blob/master/src/include/tcop/tcopprot.h#L66).
  If we try to retrieve the old handler using `signal.getsignal` we get a None object

So after going back and forth I've come to two possible solutions:
- [custom code](https://github.com/CartoDB/postgres/commit/5b159b1cce6da38c2c67d4058d544ff9bb179480) in `plpython` to make us able to reset the default signal handler after finish the CPU-intensive functions. It seems to works but I'm doing some tests yet. This option lets us call it explicitly and add it to the `finally` part of a decorator/context manager
- Reset the signal handler at the beginning of the `plpy.execute` or alike functions like [here](https://github.com/CartoDB/postgres/commit/5b159b1cce6da38c2c67d4058d544ff9bb179480#diff-4d0cb76412a1c4ee5d9c7f76ee489507R185).

I know this is not the expected solution but I think there is no other solution for this problem. If someone has another idea or solution I'm more than glad to discuss it or implement it.

**Comment by ethervoid** [comment]
Thread in the pgsql-hackers mailing list: https://www.postgresql.org/message-id/CAFYwGJ3%2BXg7EcL2nU-MxX6p%2BO6c895Pm3mYZ-b%2B9n9DffEh5MQ%40mail.gmail.com

**Comment by ethervoid** [comment]
This is the .patch for the release of our custom signal handler in PlPython: https://github.com/CartoDB/postgres/commit/c7f7c818d90b8f94103b218732ba749db6812ea9.patch

Any CR or question is welcome!

// @CartoDB/systems

**Comment by rafatower** [comment]
@luisbosque can you please add it to your sprint?

**Comment by luisbosque** [comment]
We can close this one, right?
Continue on the new one
